config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root 'static_pages#home'

  get  '/grandravine',    to: 'static_pages#OpenScadpm'

  get  '/rcm',    to: 'static_pages#Documentation'

  get  '/reports',    to: 'static_pages#Packages'

  get  '/support',    to: 'static_pages#Support'

  get  '/signup', to: 'users#new'

  get    '/login',   to: 'sessions#new'

  post   '/login',   to: 'sessions#create'

  delete '/logout',  to: 'sessions#destroy'

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 200 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :username, presence: true, length: { maximum: 40 }, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid username or password'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def OpenScadpm
  end

  def Documentation
  end

  def Support
  end

  def Packages
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Thank you for joining those envisioning a better future for Grand Ravine, Haiti!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :username, :password,
                                   :password_confirmation)
    end

    # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Grand Ravine"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Learn about <a href="https://borgenproject.org/top-five-facts-about-poverty-in-haiti/">Haiti</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Grand Ravine", grandravine_path %></li>
      <li><%= link_to "Support", support_path %></li>
      <li><%= link_to "Log in to RCM App", login_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= image_tag("Flag_of_Haiti.png", :alt => "OpenSCAD logo", id: "logo1") %>
    <%= link_to "Grand Ravine", root_path, id: "logo2" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Grand Ravine",   grandravine_path %></li>
        <li><%= link_to "RCM Application",   rcm_path %></li>
        <li><%= link_to "Support",   support_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Reports", reports_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>      
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/Documentation.html.erb
<% provide(:title, "RCM Application") %>
<div class="center jumbotron">
  <h1>RCM Application</h1>
  <h3>The Water Management Solution for Grand Ravine, Haiti</h3>
  <p>
  'RCM Application' was created with the hope of enabling the Grand Ravine slum administration to use water smartly. This was achieved with the help of an intelligent tool that can calculate the ideal usage of water based on past and predicted weather as well as water supply. Please sign up to view the most recent water reports.
  </p>
  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="home_pic">
<%= image_tag("water_haiti.jpg", :alt => "Poverty in Haiti") %>
</div>

app/views/static_pages/OpenScadpm.html.erb
<% provide(:title, "About") %>
<div class="center jumbotron">
  <h1>What is Grand Ravine?</h1>

  <p>
  Grand Ravine is a hill-side slum of the Haitian capital, Port-au-Prince. The slum sits along steeply sloping hills and is a home to roughly 20000 people. Grand Ravine faces a severe lack of clean water problem, which is a direct result of ineffective and unsustainable existing infrastructure. The RCM Application tackles this problem by analyzing how to best use water resources for everyone's benefit.
  </p>
  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="home_pic">
<%= image_tag("grand_ravine.jpg", :alt => "Poverty in Haiti") %>
</div>

app/views/static_pages/Packages.html.erb
<% provide(:title, "Reports") %>
<h1>RCM Application Report</h1>
<div class="home_pic">
<%= image_tag("samplereportpic.jpg", :alt => "Poverty in Haiti") %>
<%= image_tag("samplereportpic2.jpg", :alt => "Poverty in Haiti") %>
</div>

app/views/static_pages/Support.html.erb
<% provide(:title, "Support") %>
<div class="center jumbotron">
  <h1>Contact Us</h1>
  <h3>In case of interest, please contact: </h3>
  <p></p>
  <p>
  Sarah Leong: kl2751@columbia.edu 
  </p>
  <p>
  Stan Peceny: skp2140@columbia.edu
  </p>
  <p>
  Emma Etherington:ele2116@columbia.edu 
  </p>
  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="home_pic">
<%= image_tag("haiti_coast.jpg", :alt => "Poverty in Haiti") %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Rainwater Collection Management Application</h1>
  <h3>The Water Management Solution for Grand Ravine, Haiti</h3>
  <p>
  'RCM Application' offers a unique solution to managing water in the Grand Ravine Slum of the Haiti's capital, Port-au-Prince. The application engine uses advanced machine learning methods and data obtained from various weather predicting sources and water tank sensors to determine the best water allocation within the slum. Please sign up to view the most recent water reports.
  </p>
  <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<div class="home_pic">
<%= image_tag("poverty_haiti.jpg", :alt => "Poverty in Haiti") %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>

	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :email %>
	<%= f.email_field :email, class: 'form-control' %>

	<%= f.label :username %>
	<%= f.text_field :username, class: 'form-control' %>

	<%= f.label :password, "Password (Minimum 8 Characters)" %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmation, "Confirm Password" %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
  <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :password, "Password (Minimum 8 Characters)" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

    

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">
  <<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create Account') %>
<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>, <%= @user.email %>, <%= @user.username %>
      </h1>
    </section>
  </aside>
</div>